---
title: "all-exp2-exp3-figures"
author: "Tingying He"
date: '2023-11-15'
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Import library and functions

```{r}
library(plyr)
library(dplyr)
library(tidyr)
```


```{r}
source("CI-Functions-Bonferroni.R")
```

## Experiment 2

### Bar Chart

```{r}
mydata <- read.table("exp-data/exp2_bar.csv", header=T, sep=",")
filename_analysis <- "results/"
```

#### BeauVis Score

```{r}
##Need to refactor the data a bit

#This was a between-subjects experiment
bardf <- mydata %>% select(matches("bar|participant_id"))
bardf <- bardf %>% drop_na(beauvis_bar_geo)
bardf <- bardf %>% 
  rename(
    geometric = beauvis_bar_geo,
    iconic = beauvis_bar_icon,
    #unicolor = beauvis_bar_color
  )


##Calculating threshold CIs for the bar charts
technique_bar_geo <- bootstrapMeanCI(bardf$geometric)
technique_bar_icon <- bootstrapMeanCI(bardf$iconic)


###changing the data structure a bit
#bar chart
barData <- c()
barData$name <- c("geometric","iconic")
barData$pointEstimate <- c(technique_bar_geo[1], technique_bar_icon[1])
barData$ci.max <- c(technique_bar_geo[3], technique_bar_icon[3])
barData$ci.min <- c(technique_bar_geo[2], technique_bar_icon[2])

####plotting
#bar chart
bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
colnames(bardatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gbar <- barChart(bardatatoprint,barData$name ,nbTechs = 2, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","bar") #Avg. Thresholds. Error bars, Bootstrap 95% CIs
print(gbar)

fname <- "results/Figure4a-exp2_beauvis_bar.pdf"
ggsave(filename = fname, plot=gbar, width = 8, height= 0.8, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_beauvis_bar.csv", collapse="_")
write.csv(bardatatoprint,file=tmp)


########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_bar = bootstrapMeanCI_corr(bardf$geometric  - bardf$iconic, 1)


analysisBar <- c()
#analysisBar$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisBar$name <- c("geo-icon")
analysisBar$pointEstimate <- c(diff_geo_icon_bar[1])
analysisBar$ci.max <- c(diff_geo_icon_bar[3])
analysisBar$ci.min <- c(diff_geo_icon_bar[2])
analysisBar$level  <- c(diff_geo_icon_bar[4])
analysisBar$ci_corr.max <- c(diff_geo_icon_bar[6])
analysisBar$ci_corr.min <- c(diff_geo_icon_bar[5])


###Plotting the differences

#Bar chart
datatoprintbar <- data.frame(factor(analysisBar$name), analysisBar$pointEstimate, analysisBar$ci.min, analysisBar$ci.max, analysisBar$level, analysisBar$ci_corr.min, analysisBar$ci_corr.max)
colnames(datatoprintbar) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintbar,analysisBar$name ,nbTechs = 1, ymin = -3, ymax = 3, gray_line_interval = 1,"", "","bar") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure4d-exp2_beauvis_diff_bar.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 0.6, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_beauvis_diff_bar.csv", collapse="_")
write.csv(datatoprintbar,file=tmp)
```

#### Vibratory Effect Score

```{r}
##Need to refactor the data a bit

#This was a between-subjects experiment
bardf <- mydata %>% select(matches("bar|participant_id"))
bardf <- bardf %>% drop_na(vibratory_bar_geo)
bardf <- bardf %>% 
  rename(
    geometric = vibratory_bar_geo,
    iconic = vibratory_bar_icon,
    #unicolor = vibratory_bar_color
  )


##Calculating threshold CIs for the bar charts
technique_bar_geo <- bootstrapMeanCI(bardf$geometric)
technique_bar_icon <- bootstrapMeanCI(bardf$iconic)


###changing the data structure a bit
#bar chart
barData <- c()
barData$name <- c("geometric","iconic")
barData$pointEstimate <- c(technique_bar_geo[1], technique_bar_icon[1])
barData$ci.max <- c(technique_bar_geo[3], technique_bar_icon[3])
barData$ci.min <- c(technique_bar_geo[2], technique_bar_icon[2])

####plotting
#bar chart
bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
colnames(bardatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gbar <- barChart(bardatatoprint,barData$name ,nbTechs = 2, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","bar") #Avg. Thresholds. Error bars, Bootstrap 95% CIs
print(gbar)

fname <- "results/Figure5a-exp2_vibratory_bar.pdf"
ggsave(filename = fname, plot=gbar, width = 8, height= 0.8, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_vibratory_bar.csv", collapse="_")
write.csv(bardatatoprint,file=tmp)


########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_bar = bootstrapMeanCI_corr(bardf$geometric  - bardf$iconic, 1)


analysisBar <- c()
#analysisBar$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisBar$name <- c("geo-icon")
analysisBar$pointEstimate <- c(diff_geo_icon_bar[1])
analysisBar$ci.max <- c(diff_geo_icon_bar[3])
analysisBar$ci.min <- c(diff_geo_icon_bar[2])
analysisBar$level  <- c(diff_geo_icon_bar[4])
analysisBar$ci_corr.max <- c(diff_geo_icon_bar[6])
analysisBar$ci_corr.min <- c(diff_geo_icon_bar[5])


###Plotting the differences

#Bar chart
datatoprintbar <- data.frame(factor(analysisBar$name), analysisBar$pointEstimate, analysisBar$ci.min, analysisBar$ci.max, analysisBar$level, analysisBar$ci_corr.min, analysisBar$ci_corr.max)
colnames(datatoprintbar) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintbar,analysisBar$name ,nbTechs = 1, ymin = -3, ymax = 3, gray_line_interval = 1,"", "","bar") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure5d-exp2_vibratory_diff_bar.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 0.6, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_vibratory_diff_bar.csv", collapse="_")
write.csv(datatoprintbar,file=tmp)
```


### Pie Chart

```{r}
mydata <- read.table("exp-data/exp2_pie.csv", header=T, sep=",")
filename_analysis <- "results/"
```


#### BeauVis Score

```{r}

##Need to refactor the data a bit

#This was a between-subjects experiment
piedf <- mydata %>% select(matches("pie|participant_id"))
piedf <- piedf %>% drop_na(beauvis_pie_geo)
piedf <- piedf %>% 
  rename(
    geometric = beauvis_pie_geo,
    iconic = beauvis_pie_icon,
  )


##Calculating threshold CIs for the pie charts
technique_pie_geo <- bootstrapMeanCI(piedf$geometric)
technique_pie_icon <- bootstrapMeanCI(piedf$iconic)

###changing the data structure a bit
#pie chart
pieData <- c()
pieData$name <- c("geometric","iconic")
pieData$pointEstimate <- c(technique_pie_geo[1], technique_pie_icon[1])
pieData$ci.max <- c(technique_pie_geo[3], technique_pie_icon[3])
pieData$ci.min <- c(technique_pie_geo[2], technique_pie_icon[2])


####plotting
#pie chart
piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
colnames(piedatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gpie <- barChart(piedatatoprint,pieData$name ,nbTechs = 2, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","pie") #Avg. Thresholds. Error pies, Bootstrap 95% CIs
print(gpie)

fname <- "results/Figure4b-exp2_beauvis_pie.pdf"
ggsave(filename = fname, plot=gpie, width = 8, height= 0.8, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_beauvis_pie.csv", collapse="_")
write.csv(piedatatoprint,file=tmp)


########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_pie = bootstrapMeanCI_corr(piedf$geometric  - piedf$iconic, 1)


analysisPie <- c()
#analysisPie$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisPie$name <- c("geo-icon")
analysisPie$pointEstimate <- c(diff_geo_icon_pie[1])
analysisPie$ci.max <- c(diff_geo_icon_pie[3])
analysisPie$ci.min <- c(diff_geo_icon_pie[2])
analysisPie$level  <- c(diff_geo_icon_pie[4])
analysisPie$ci_corr.max <- c(diff_geo_icon_pie[6])
analysisPie$ci_corr.min <- c(diff_geo_icon_pie[5])


###Plotting the differences

#Pie chart
datatoprintpie <- data.frame(factor(analysisPie$name), analysisPie$pointEstimate, analysisPie$ci.min, analysisPie$ci.max, analysisPie$level, analysisPie$ci_corr.min, analysisPie$ci_corr.max)
colnames(datatoprintpie) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintpie,analysisPie$name ,nbTechs = 1, ymin = -3, ymax = 3, gray_line_interval = 1, "", "","pie") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure4e-exp2_beauvis_diff_pie.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 0.6, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_beauvis_diff_pie.csv", collapse="_")
write.csv(datatoprintpie,file=tmp)

```


#### Vibratory Effect Score

```{r}
##Need to refactor the data a bit

#This was a between-subjects experiment
piedf <- mydata %>% select(matches("pie|participant_id"))
piedf <- piedf %>% drop_na(vibratory_pie_geo)
piedf <- piedf %>% 
  rename(
    geometric = vibratory_pie_geo,
    iconic = vibratory_pie_icon,
  )


##Calculating threshold CIs for the pie charts
technique_pie_geo <- bootstrapMeanCI(piedf$geometric)
technique_pie_icon <- bootstrapMeanCI(piedf$iconic)

###changing the data structure a bit
#pie chart
pieData <- c()
pieData$name <- c("geometric","iconic")
pieData$pointEstimate <- c(technique_pie_geo[1], technique_pie_icon[1])
pieData$ci.max <- c(technique_pie_geo[3], technique_pie_icon[3])
pieData$ci.min <- c(technique_pie_geo[2], technique_pie_icon[2])


####plotting
#pie chart
piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
colnames(piedatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gpie <- barChart(piedatatoprint,pieData$name ,nbTechs = 2, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","pie") #Avg. Thresholds. Error pies, Bootstrap 95% CIs
print(gpie)

fname <- "results/Figure5b-exp2_vibratory_pie.pdf"
ggsave(filename = fname, plot=gpie, width = 8, height= 0.8, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_vibratory_pie.csv", collapse="_")
write.csv(piedatatoprint,file=tmp)


########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_pie = bootstrapMeanCI_corr(piedf$geometric  - piedf$iconic, 1)


analysisPie <- c()
#analysisPie$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisPie$name <- c("geo-icon")
analysisPie$pointEstimate <- c(diff_geo_icon_pie[1])
analysisPie$ci.max <- c(diff_geo_icon_pie[3])
analysisPie$ci.min <- c(diff_geo_icon_pie[2])
analysisPie$level  <- c(diff_geo_icon_pie[4])
analysisPie$ci_corr.max <- c(diff_geo_icon_pie[6])
analysisPie$ci_corr.min <- c(diff_geo_icon_pie[5])


###Plotting the differences

#Pie chart
datatoprintpie <- data.frame(factor(analysisPie$name), analysisPie$pointEstimate, analysisPie$ci.min, analysisPie$ci.max, analysisPie$level, analysisPie$ci_corr.min, analysisPie$ci_corr.max)
colnames(datatoprintpie) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintpie,analysisPie$name ,nbTechs = 1, ymin = -3, ymax = 3, gray_line_interval = 1, "", "","pie") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure5e-exp2_vibratory_diff_pie.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 0.6, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_vibratory_diff_pie.csv", collapse="_")
write.csv(datatoprintpie,file=tmp)

```



### Map


```{r}
mydata <- read.table("exp-data/exp2_map.csv", header=T, sep=",")
filename_analysis <- "results/"
```


#### BeauVis Score

```{r}



##Need to refactor the data a bit

#This was a between-subjects experiment
mapdf <- mydata %>% select(matches("map|participant_id"))
mapdf <- mapdf %>% drop_na(beauvis_map_geo)
mapdf <- mapdf %>% 
  rename(
    geometric = beauvis_map_geo,
    iconic = beauvis_map_icon,
    #unicolor = beauvis_map_color
  )


##Calculating threshold CIs for the map charts
technique_map_geo <- bootstrapMeanCI(mapdf$geometric)
technique_map_icon <- bootstrapMeanCI(mapdf$iconic)
#technique_map_unicolor <- bootstrapMeanCI(mapdf$unicolor)


###changing the data structure a bit
#map chart
mapData <- c()
mapData$name <- c("geometric","iconic")
mapData$pointEstimate <- c(technique_map_geo[1], technique_map_icon[1])
mapData$ci.max <- c(technique_map_geo[3], technique_map_icon[3])
mapData$ci.min <- c(technique_map_geo[2], technique_map_icon[2])


####plotting
#map chart
mapdatatoprint <- data.frame(factor(mapData$name),mapData$pointEstimate, mapData$ci.min, mapData$ci.max)
colnames(mapdatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gmap <- barChart(mapdatatoprint,mapData$name ,nbTechs = 2, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","map") #Avg. Thresholds. Error maps, Bootstrap 95% CIs
print(gmap)

fname <- "results/Figure4c-exp2_beauvis_map.pdf"
ggsave(filename = fname, plot=gmap, width = 8, height= 0.8, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_beauvis_map.csv", collapse="_")
write.csv(mapdatatoprint,file=tmp)


########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_map = bootstrapMeanCI_corr(mapdf$geometric  - mapdf$iconic, 1)



analysisMap <- c()
#analysisMap$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisMap$name <- c("geo-icon")
analysisMap$pointEstimate <- c(diff_geo_icon_map[1])
analysisMap$ci.max <- c(diff_geo_icon_map[3])
analysisMap$ci.min <- c(diff_geo_icon_map[2])
analysisMap$level  <- c(diff_geo_icon_map[4])
analysisMap$ci_corr.max <- c(diff_geo_icon_map[6])
analysisMap$ci_corr.min <- c(diff_geo_icon_map[5])


###Plotting the differences

#Map chart
datatoprintmap <- data.frame(factor(analysisMap$name), analysisMap$pointEstimate, analysisMap$ci.min, analysisMap$ci.max, analysisMap$level, analysisMap$ci_corr.min, analysisMap$ci_corr.max)
colnames(datatoprintmap) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintmap,analysisMap$name ,nbTechs = 1, ymin = -3, ymax = 3, gray_line_interval = 1, "", "","map") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure4f-exp2_beauvis_diff_map.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 0.6, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_beauvis_diff_map.csv", collapse="_")
write.csv(datatoprintmap,file=tmp)


```

#### Vibratory Effect Score

```{r}


##Need to refactor the data a bit

#This was a between-subjects experiment
mapdf <- mydata %>% select(matches("map|participant_id"))
mapdf <- mapdf %>% drop_na(vibratory_map_geo)
mapdf <- mapdf %>% 
  rename(
    geometric = vibratory_map_geo,
    iconic = vibratory_map_icon,
    #unicolor = vibratory_map_color
  )


##Calculating threshold CIs for the map charts
technique_map_geo <- bootstrapMeanCI(mapdf$geometric)
technique_map_icon <- bootstrapMeanCI(mapdf$iconic)
#technique_map_unicolor <- bootstrapMeanCI(mapdf$unicolor)


###changing the data structure a bit
#map chart
mapData <- c()
mapData$name <- c("geometric","iconic")
mapData$pointEstimate <- c(technique_map_geo[1], technique_map_icon[1])
mapData$ci.max <- c(technique_map_geo[3], technique_map_icon[3])
mapData$ci.min <- c(technique_map_geo[2], technique_map_icon[2])


####plotting
#map chart
mapdatatoprint <- data.frame(factor(mapData$name),mapData$pointEstimate, mapData$ci.min, mapData$ci.max)
colnames(mapdatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gmap <- barChart(mapdatatoprint,mapData$name ,nbTechs = 2, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","map") #Avg. Thresholds. Error maps, Bootstrap 95% CIs
print(gmap)

fname <- "results/Figure5c-exp2_vibratory_map.pdf"
ggsave(filename = fname, plot=gmap, width = 8, height= 0.8, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_vibratory_map.csv", collapse="_")
write.csv(mapdatatoprint,file=tmp)


########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_map = bootstrapMeanCI_corr(mapdf$geometric  - mapdf$iconic, 1)



analysisMap <- c()
#analysisMap$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisMap$name <- c("geo-icon")
analysisMap$pointEstimate <- c(diff_geo_icon_map[1])
analysisMap$ci.max <- c(diff_geo_icon_map[3])
analysisMap$ci.min <- c(diff_geo_icon_map[2])
analysisMap$level  <- c(diff_geo_icon_map[4])
analysisMap$ci_corr.max <- c(diff_geo_icon_map[6])
analysisMap$ci_corr.min <- c(diff_geo_icon_map[5])


###Plotting the differences

#Map chart
datatoprintmap <- data.frame(factor(analysisMap$name), analysisMap$pointEstimate, analysisMap$ci.min, analysisMap$ci.max, analysisMap$level, analysisMap$ci_corr.min, analysisMap$ci_corr.max)
colnames(datatoprintmap) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintmap,analysisMap$name ,nbTechs = 1, ymin = -3, ymax = 3, gray_line_interval = 1, "", "","map") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure5f-exp2_vibratory_diff_map.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 0.6, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp2_vibratory_diff_map.csv", collapse="_")
write.csv(datatoprintmap,file=tmp)

```


## Experiment 3

### Correct Rate

```{r}

mydata <- read.table("exp-data/correct_rate.csv", header=T, sep=",")
filename_analysis <- "results/"

##Need to refactor the data a bit

#This was a between-subjects experiment
bardf <- mydata %>% select(matches("bar|participant_id"))
bardf <- bardf %>% drop_na(correct_rate_bar_geo)
bardf <- bardf %>% 
  rename(
    geometric = correct_rate_bar_geo,
    iconic = correct_rate_bar_icon,
    unicolor = correct_rate_bar_color
  )

piedf <- mydata %>% select(matches("pie|participant_id"))
piedf <- piedf %>% drop_na(correct_rate_pie_geo)
piedf <- piedf %>% 
  rename(
    geometric = correct_rate_pie_geo,
    iconic = correct_rate_pie_icon,
    unicolor = correct_rate_pie_color
  )


##Calculating threshold CIs for the bar charts
technique_bar_geo <- bootstrapMeanCI(bardf$geometric)
technique_bar_icon <- bootstrapMeanCI(bardf$iconic)
technique_bar_unicolor <- bootstrapMeanCI(bardf$unicolor)

##Calculating threshold CIs for the pie charts
technique_pie_geo <- bootstrapMeanCI(piedf$geometric)
technique_pie_icon <- bootstrapMeanCI(piedf$iconic)
technique_pie_unicolor <- bootstrapMeanCI(piedf$unicolor)


###changing the data structure a bit
#bar chart
barData <- c()
barData$name <- c("geometric","iconic","unicolor")
barData$pointEstimate <- c(technique_bar_geo[1], technique_bar_icon[1],technique_bar_unicolor[1])
barData$ci.max <- c(technique_bar_geo[3], technique_bar_icon[3],technique_bar_unicolor[3])
barData$ci.min <- c(technique_bar_geo[2], technique_bar_icon[2],technique_bar_unicolor[2])

#pie chart
pieData <- c()
pieData$name <- c("geometric","iconic","unicolor")
pieData$pointEstimate <- c(technique_pie_geo[1], technique_pie_icon[1],technique_pie_unicolor[1])
pieData$ci.max <- c(technique_pie_geo[3], technique_pie_icon[3],technique_pie_unicolor[3])
pieData$ci.min <- c(technique_pie_geo[2], technique_pie_icon[2],technique_pie_unicolor[2])



####plotting
#bar chart
bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
colnames(bardatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gbar <- barChart(bardatatoprint,barData$name ,nbTechs = 3, ymin = 0, ymax = 100, gray_line_interval = 10, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gbar)

fname <- "results/Figure6a-exp3_correct_rate_bar.pdf"
ggsave(filename = fname, plot=gbar, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_correct_rate_bar.csv", collapse="_")
write.csv(bardatatoprint,file=tmp)



#pie chart
piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
colnames(piedatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gpie <- barChart(piedatatoprint,pieData$name ,nbTechs = 3, ymin = 0, ymax = 100, gray_line_interval = 10,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gpie)
fname <- "results/Figure6b-exp3_correct_rate_pie.pdf"
ggsave(filename = fname, plot=gpie, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_correct_rate_pie.csv", collapse="_")
write.csv(piedatatoprint,file=tmp)

########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_bar = bootstrapMeanCI_corr(bardf$geometric  - bardf$iconic, 3)
diff_geo_uni_bar  = bootstrapMeanCI_corr(bardf$geometric  - bardf$unicolor, 3)
diff_uni_icon_bar = bootstrapMeanCI_corr(bardf$unicolor - bardf$iconic, 3)

diff_geo_icon_pie = bootstrapMeanCI_corr(piedf$geometric  - piedf$iconic, 3)
diff_geo_uni_pie  = bootstrapMeanCI_corr(piedf$geometric  - piedf$unicolor, 3)
diff_uni_icon_pie = bootstrapMeanCI_corr(piedf$unicolor - piedf$iconic, 3)


analysisBar <- c()
analysisBar$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisBar$pointEstimate <- c(diff_geo_icon_bar[1], diff_geo_uni_bar[1], diff_uni_icon_bar[1])
analysisBar$ci.max <- c(diff_geo_icon_bar[3], diff_geo_uni_bar[3], diff_uni_icon_bar[3])
analysisBar$ci.min <- c(diff_geo_icon_bar[2], diff_geo_uni_bar[2], diff_uni_icon_bar[2])
analysisBar$level  <- c(diff_geo_icon_bar[4], diff_geo_uni_bar[4], diff_uni_icon_bar[4])
analysisBar$ci_corr.max <- c(diff_geo_icon_bar[6], diff_geo_uni_bar[6], diff_uni_icon_bar[6])
analysisBar$ci_corr.min <- c(diff_geo_icon_bar[5], diff_geo_uni_bar[5], diff_uni_icon_bar[5])

analysisPie <- c()
analysisPie$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisPie$pointEstimate <- c(diff_geo_icon_pie[1], diff_geo_uni_pie[1], diff_uni_icon_pie[1])
analysisPie$ci.max <- c(diff_geo_icon_pie[3], diff_geo_uni_pie[3], diff_uni_icon_pie[3])
analysisPie$ci.min <- c(diff_geo_icon_pie[2], diff_geo_uni_pie[2], diff_uni_icon_pie[2])
analysisPie$level  <- c(diff_geo_icon_pie[4], diff_geo_uni_pie[4], diff_uni_icon_pie[4])
analysisPie$ci_corr.max <- c(diff_geo_icon_pie[6], diff_geo_uni_pie[6], diff_uni_icon_pie[6])
analysisPie$ci_corr.min <- c(diff_geo_icon_pie[5], diff_geo_uni_pie[5], diff_uni_icon_pie[5])


###Plotting the differences

#Bar chart
datatoprintbar <- data.frame(factor(analysisBar$name), analysisBar$pointEstimate, analysisBar$ci.min, analysisBar$ci.max, analysisBar$level, analysisBar$ci_corr.min, analysisBar$ci_corr.max)
colnames(datatoprintbar) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintbar,analysisBar$name ,nbTechs = 3, ymin = -10, ymax = 10,  gray_line_interval = 5,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure6c-exp3_correct_rate_diff_bar.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_correct_rate_diff_bar.csv", collapse="_")
write.csv(datatoprintbar,file=tmp)

#Pie chart
datatoprintpie <- data.frame(factor(analysisPie$name), analysisPie$pointEstimate, analysisPie$ci.min, analysisPie$ci.max, analysisPie$level, analysisPie$ci_corr.min, analysisPie$ci_corr.max)
colnames(datatoprintpie) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintpie,analysisPie$name ,nbTechs = 3, ymin = -10, ymax = 10,  gray_line_interval = 5, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure6d-exp3_correct_rate_diff_pie.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_correct_rate_diff_pie.csv", collapse="_")
write.csv(datatoprintpie,file=tmp)

```

### Response Time

```{r}

mydata <- read.table("exp-data/response_time.csv", header=T, sep=",")
filename_analysis <- "results/"

##Need to refactor the data a bit

#This was a between-subjects experiment
bardf <- mydata %>% select(matches("bar|participant_id"))
bardf <- bardf %>% drop_na(response_time_bar_geo)
bardf <- bardf %>% 
  rename(
    geometric = response_time_bar_geo,
    iconic = response_time_bar_icon,
    unicolor = response_time_bar_color
  )

piedf <- mydata %>% select(matches("pie|participant_id"))
piedf <- piedf %>% drop_na(response_time_pie_geo)
piedf <- piedf %>% 
  rename(
    geometric = response_time_pie_geo,
    iconic = response_time_pie_icon,
    unicolor = response_time_pie_color
  )


##Calculating threshold CIs for the bar charts
technique_bar_geo <- bootstrapMeanCI(bardf$geometric)
technique_bar_icon <- bootstrapMeanCI(bardf$iconic)
technique_bar_unicolor <- bootstrapMeanCI(bardf$unicolor)

##Calculating threshold CIs for the pie charts
technique_pie_geo <- bootstrapMeanCI(piedf$geometric)
technique_pie_icon <- bootstrapMeanCI(piedf$iconic)
technique_pie_unicolor <- bootstrapMeanCI(piedf$unicolor)


###changing the data structure a bit
#bar chart
barData <- c()
barData$name <- c("geometric","iconic","unicolor")
barData$pointEstimate <- c(technique_bar_geo[1], technique_bar_icon[1],technique_bar_unicolor[1])
barData$ci.max <- c(technique_bar_geo[3], technique_bar_icon[3],technique_bar_unicolor[3])
barData$ci.min <- c(technique_bar_geo[2], technique_bar_icon[2],technique_bar_unicolor[2])

#pie chart
pieData <- c()
pieData$name <- c("geometric","iconic","unicolor")
pieData$pointEstimate <- c(technique_pie_geo[1], technique_pie_icon[1],technique_pie_unicolor[1])
pieData$ci.max <- c(technique_pie_geo[3], technique_pie_icon[3],technique_pie_unicolor[3])
pieData$ci.min <- c(technique_pie_geo[2], technique_pie_icon[2],technique_pie_unicolor[2])

##preparting to print
#bar chart
#bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
#colnames(bardatatoprint) <- c("technique", "time", "lowerBound_CI", "upperBound_CI ")

#pie chart
#piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
#colnames(piedatatoprint) <- c("technique", "time", "lowerBound_CI", "upperBound_CI ")


####plotting
#bar chart
bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
colnames(bardatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gbar <- barChart(bardatatoprint,barData$name ,nbTechs = 3, ymin = 0, ymax = 3000, gray_line_interval = 500, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gbar)

fname <- "results/Figure7a-exp3_response_time_bar.pdf"
ggsave(filename = fname, plot=gbar, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_response_time_bar.csv", collapse="_")
write.csv(bardatatoprint,file=tmp)



#pie chart
piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
colnames(piedatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gpie <- barChart(piedatatoprint,pieData$name ,nbTechs = 3, ymin = 0, ymax = 3000, gray_line_interval = 500,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gpie)
fname <- "results/Figure7b-exp3_response_time_pie.pdf"
ggsave(filename = fname, plot=gpie, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_response_time_pie.csv", collapse="_")
write.csv(piedatatoprint,file=tmp)

########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_bar = bootstrapMeanCI_corr(bardf$geometric  - bardf$iconic, 3)
diff_geo_uni_bar  = bootstrapMeanCI_corr(bardf$geometric  - bardf$unicolor, 3)
diff_uni_icon_bar = bootstrapMeanCI_corr(bardf$unicolor - bardf$iconic, 3)

diff_geo_icon_pie = bootstrapMeanCI_corr(piedf$geometric  - piedf$iconic, 3)
diff_geo_uni_pie  = bootstrapMeanCI_corr(piedf$geometric  - piedf$unicolor, 3)
diff_uni_icon_pie = bootstrapMeanCI_corr(piedf$unicolor - piedf$iconic, 3)


analysisBar <- c()
analysisBar$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisBar$pointEstimate <- c(diff_geo_icon_bar[1], diff_geo_uni_bar[1], diff_uni_icon_bar[1])
analysisBar$ci.max <- c(diff_geo_icon_bar[3], diff_geo_uni_bar[3], diff_uni_icon_bar[3])
analysisBar$ci.min <- c(diff_geo_icon_bar[2], diff_geo_uni_bar[2], diff_uni_icon_bar[2])
analysisBar$level  <- c(diff_geo_icon_bar[4], diff_geo_uni_bar[4], diff_uni_icon_bar[4])
analysisBar$ci_corr.max <- c(diff_geo_icon_bar[6], diff_geo_uni_bar[6], diff_uni_icon_bar[6])
analysisBar$ci_corr.min <- c(diff_geo_icon_bar[5], diff_geo_uni_bar[5], diff_uni_icon_bar[5])

analysisPie <- c()
analysisPie$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisPie$pointEstimate <- c(diff_geo_icon_pie[1], diff_geo_uni_pie[1], diff_uni_icon_pie[1])
analysisPie$ci.max <- c(diff_geo_icon_pie[3], diff_geo_uni_pie[3], diff_uni_icon_pie[3])
analysisPie$ci.min <- c(diff_geo_icon_pie[2], diff_geo_uni_pie[2], diff_uni_icon_pie[2])
analysisPie$level  <- c(diff_geo_icon_pie[4], diff_geo_uni_pie[4], diff_uni_icon_pie[4])
analysisPie$ci_corr.max <- c(diff_geo_icon_pie[6], diff_geo_uni_pie[6], diff_uni_icon_pie[6])
analysisPie$ci_corr.min <- c(diff_geo_icon_pie[5], diff_geo_uni_pie[5], diff_uni_icon_pie[5])


###Plotting the differences

#Bar chart
datatoprintbar <- data.frame(factor(analysisBar$name), analysisBar$pointEstimate, analysisBar$ci.min, analysisBar$ci.max, analysisBar$level, analysisBar$ci_corr.min, analysisBar$ci_corr.max)
colnames(datatoprintbar) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintbar,analysisBar$name ,nbTechs = 3, ymin = -400, ymax = 400,  gray_line_interval = 100,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure7c-exp3_response_time_diff_bar.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_response_time_diff_bar.csv", collapse="_")
write.csv(datatoprintbar,file=tmp)

#Pie chart
datatoprintpie <- data.frame(factor(analysisPie$name), analysisPie$pointEstimate, analysisPie$ci.min, analysisPie$ci.max, analysisPie$level, analysisPie$ci_corr.min, analysisPie$ci_corr.max)
colnames(datatoprintpie) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintpie,analysisPie$name ,nbTechs = 3, ymin = -400, ymax = 400,  gray_line_interval = 100, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure7d-exp3_response_time_diff_pie.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_response_time_diff_pie.csv", collapse="_")
write.csv(datatoprintpie,file=tmp)


```


### Readability scores

```{r}


mydata <- read.table("exp-data/readable.csv", header=T, sep=",")
filename_analysis <- "results/"

##Need to refactor the data a bit

#This was a between-subjects experiment
bardf <- mydata %>% select(matches("bar|participant_id"))
bardf <- bardf %>% drop_na(readable_bar_geo)
bardf <- bardf %>% 
  rename(
    geometric = readable_bar_geo,
    iconic = readable_bar_icon,
    unicolor = readable_bar_color
  )

piedf <- mydata %>% select(matches("pie|participant_id"))
piedf <- piedf %>% drop_na(readable_pie_geo)
piedf <- piedf %>% 
  rename(
    geometric = readable_pie_geo,
    iconic = readable_pie_icon,
    unicolor = readable_pie_color
  )


##Calculating threshold CIs for the bar charts
technique_bar_geo <- bootstrapMeanCI(bardf$geometric)
technique_bar_icon <- bootstrapMeanCI(bardf$iconic)
technique_bar_unicolor <- bootstrapMeanCI(bardf$unicolor)

##Calculating threshold CIs for the pie charts
technique_pie_geo <- bootstrapMeanCI(piedf$geometric)
technique_pie_icon <- bootstrapMeanCI(piedf$iconic)
technique_pie_unicolor <- bootstrapMeanCI(piedf$unicolor)


###changing the data structure a bit
#bar chart
barData <- c()
barData$name <- c("geometric","iconic","unicolor")
barData$pointEstimate <- c(technique_bar_geo[1], technique_bar_icon[1],technique_bar_unicolor[1])
barData$ci.max <- c(technique_bar_geo[3], technique_bar_icon[3],technique_bar_unicolor[3])
barData$ci.min <- c(technique_bar_geo[2], technique_bar_icon[2],technique_bar_unicolor[2])

#pie chart
pieData <- c()
pieData$name <- c("geometric","iconic","unicolor")
pieData$pointEstimate <- c(technique_pie_geo[1], technique_pie_icon[1],technique_pie_unicolor[1])
pieData$ci.max <- c(technique_pie_geo[3], technique_pie_icon[3],technique_pie_unicolor[3])
pieData$ci.min <- c(technique_pie_geo[2], technique_pie_icon[2],technique_pie_unicolor[2])

##preparting to print
#bar chart
#bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
#colnames(bardatatoprint) <- c("technique", "time", "lowerBound_CI", "upperBound_CI ")

#pie chart
#piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
#colnames(piedatatoprint) <- c("technique", "time", "lowerBound_CI", "upperBound_CI ")


####plotting
#bar chart
bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
colnames(bardatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gbar <- barChart(bardatatoprint,barData$name ,nbTechs = 3, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gbar)

fname <- "results/Figure8a-exp3_readable_bar.pdf"
ggsave(filename = fname, plot=gbar, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_readable_bar.csv", collapse="_")
write.csv(bardatatoprint,file=tmp)



#pie chart
piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
colnames(piedatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gpie <- barChart(piedatatoprint,pieData$name ,nbTechs = 3, ymin = 1, ymax = 7, gray_line_interval = 1,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gpie)
fname <- "results/Figure8b-exp3_readable_pie.pdf"
ggsave(filename = fname, plot=gpie, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_readable_pie.csv", collapse="_")
write.csv(piedatatoprint,file=tmp)

########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_bar = bootstrapMeanCI_corr(bardf$geometric  - bardf$iconic, 3)
diff_geo_uni_bar  = bootstrapMeanCI_corr(bardf$geometric  - bardf$unicolor, 3)
diff_uni_icon_bar = bootstrapMeanCI_corr(bardf$unicolor - bardf$iconic, 3)

diff_geo_icon_pie = bootstrapMeanCI_corr(piedf$geometric  - piedf$iconic, 3)
diff_geo_uni_pie  = bootstrapMeanCI_corr(piedf$geometric  - piedf$unicolor, 3)
diff_uni_icon_pie = bootstrapMeanCI_corr(piedf$unicolor - piedf$iconic, 3)


analysisBar <- c()
analysisBar$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisBar$pointEstimate <- c(diff_geo_icon_bar[1], diff_geo_uni_bar[1], diff_uni_icon_bar[1])
analysisBar$ci.max <- c(diff_geo_icon_bar[3], diff_geo_uni_bar[3], diff_uni_icon_bar[3])
analysisBar$ci.min <- c(diff_geo_icon_bar[2], diff_geo_uni_bar[2], diff_uni_icon_bar[2])
analysisBar$level  <- c(diff_geo_icon_bar[4], diff_geo_uni_bar[4], diff_uni_icon_bar[4])
analysisBar$ci_corr.max <- c(diff_geo_icon_bar[6], diff_geo_uni_bar[6], diff_uni_icon_bar[6])
analysisBar$ci_corr.min <- c(diff_geo_icon_bar[5], diff_geo_uni_bar[5], diff_uni_icon_bar[5])

analysisPie <- c()
analysisPie$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisPie$pointEstimate <- c(diff_geo_icon_pie[1], diff_geo_uni_pie[1], diff_uni_icon_pie[1])
analysisPie$ci.max <- c(diff_geo_icon_pie[3], diff_geo_uni_pie[3], diff_uni_icon_pie[3])
analysisPie$ci.min <- c(diff_geo_icon_pie[2], diff_geo_uni_pie[2], diff_uni_icon_pie[2])
analysisPie$level  <- c(diff_geo_icon_pie[4], diff_geo_uni_pie[4], diff_uni_icon_pie[4])
analysisPie$ci_corr.max <- c(diff_geo_icon_pie[6], diff_geo_uni_pie[6], diff_uni_icon_pie[6])
analysisPie$ci_corr.min <- c(diff_geo_icon_pie[5], diff_geo_uni_pie[5], diff_uni_icon_pie[5])


###Plotting the differences

#Bar chart
datatoprintbar <- data.frame(factor(analysisBar$name), analysisBar$pointEstimate, analysisBar$ci.min, analysisBar$ci.max, analysisBar$level, analysisBar$ci_corr.min, analysisBar$ci_corr.max)
colnames(datatoprintbar) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintbar,analysisBar$name ,nbTechs = 3, ymin = -3, ymax = 3,  gray_line_interval = 1,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure8c-exp3_readable_diff_bar.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_readable_diff_bar.csv", collapse="_")
write.csv(datatoprintbar,file=tmp)

#Pie chart
datatoprintpie <- data.frame(factor(analysisPie$name), analysisPie$pointEstimate, analysisPie$ci.min, analysisPie$ci.max, analysisPie$level, analysisPie$ci_corr.min, analysisPie$ci_corr.max)
colnames(datatoprintpie) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintpie,analysisPie$name ,nbTechs = 3, ymin = -3, ymax = 3,  gray_line_interval = 1, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure8d-exp3_readable_diff_pie.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_readable_diff_pie.csv", collapse="_")
write.csv(datatoprintpie,file=tmp)


```


### BeauVis Score

```{r}

mydata <- read.table("exp-data/beauvis.csv", header=T, sep=",")
filename_analysis <- "results/"

##Need to refactor the data a bit

#This was a between-subjects experiment
bardf <- mydata %>% select(matches("bar|participant_id"))
bardf <- bardf %>% drop_na(beauvis_bar_geo)
bardf <- bardf %>% 
  rename(
    geometric = beauvis_bar_geo,
    iconic = beauvis_bar_icon,
    unicolor = beauvis_bar_color
  )

piedf <- mydata %>% select(matches("pie|participant_id"))
piedf <- piedf %>% drop_na(beauvis_pie_geo)
piedf <- piedf %>% 
  rename(
    geometric = beauvis_pie_geo,
    iconic = beauvis_pie_icon,
    unicolor = beauvis_pie_color
  )


##Calculating threshold CIs for the bar charts
technique_bar_geo <- bootstrapMeanCI(bardf$geometric)
technique_bar_icon <- bootstrapMeanCI(bardf$iconic)
technique_bar_unicolor <- bootstrapMeanCI(bardf$unicolor)

##Calculating threshold CIs for the pie charts
technique_pie_geo <- bootstrapMeanCI(piedf$geometric)
technique_pie_icon <- bootstrapMeanCI(piedf$iconic)
technique_pie_unicolor <- bootstrapMeanCI(piedf$unicolor)


###changing the data structure a bit
#bar chart
barData <- c()
barData$name <- c("geometric","iconic","unicolor")
barData$pointEstimate <- c(technique_bar_geo[1], technique_bar_icon[1],technique_bar_unicolor[1])
barData$ci.max <- c(technique_bar_geo[3], technique_bar_icon[3],technique_bar_unicolor[3])
barData$ci.min <- c(technique_bar_geo[2], technique_bar_icon[2],technique_bar_unicolor[2])

#pie chart
pieData <- c()
pieData$name <- c("geometric","iconic","unicolor")
pieData$pointEstimate <- c(technique_pie_geo[1], technique_pie_icon[1],technique_pie_unicolor[1])
pieData$ci.max <- c(technique_pie_geo[3], technique_pie_icon[3],technique_pie_unicolor[3])
pieData$ci.min <- c(technique_pie_geo[2], technique_pie_icon[2],technique_pie_unicolor[2])

##preparting to print
#bar chart
#bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
#colnames(bardatatoprint) <- c("technique", "time", "lowerBound_CI", "upperBound_CI ")

#pie chart
#piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
#colnames(piedatatoprint) <- c("technique", "time", "lowerBound_CI", "upperBound_CI ")


####plotting
#bar chart
bardatatoprint <- data.frame(factor(barData$name),barData$pointEstimate, barData$ci.min, barData$ci.max)
colnames(bardatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gbar <- barChart(bardatatoprint,barData$name ,nbTechs = 3, ymin = 1, ymax = 7, gray_line_interval = 1, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gbar)

fname <- "results/Figure9a-exp3_beauvis_bar.pdf"
ggsave(filename = fname, plot=gbar, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_beauvis_bar.csv", collapse="_")
write.csv(bardatatoprint,file=tmp)



#pie chart
piedatatoprint <- data.frame(factor(pieData$name),pieData$pointEstimate, pieData$ci.min, pieData$ci.max)
colnames(piedatatoprint) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI ")
gpie <- barChart(piedatatoprint,pieData$name ,nbTechs = 3, ymin = 1, ymax = 7, gray_line_interval = 1,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(gpie)
fname <- "results/Figure9b-exp3_beauvis_pie.pdf"
ggsave(filename = fname, plot=gpie, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_beauvis_pie.csv", collapse="_")
write.csv(piedatatoprint,file=tmp)

########################

# CIs with adapted alpha value for multiple comparisons --- calculate the differences between techniques for each chart separately
diff_geo_icon_bar = bootstrapMeanCI_corr(bardf$geometric  - bardf$iconic, 3)
diff_geo_uni_bar  = bootstrapMeanCI_corr(bardf$geometric  - bardf$unicolor, 3)
diff_uni_icon_bar = bootstrapMeanCI_corr(bardf$unicolor - bardf$iconic, 3)

diff_geo_icon_pie = bootstrapMeanCI_corr(piedf$geometric  - piedf$iconic, 3)
diff_geo_uni_pie  = bootstrapMeanCI_corr(piedf$geometric  - piedf$unicolor, 3)
diff_uni_icon_pie = bootstrapMeanCI_corr(piedf$unicolor - piedf$iconic, 3)


analysisBar <- c()
analysisBar$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisBar$pointEstimate <- c(diff_geo_icon_bar[1], diff_geo_uni_bar[1], diff_uni_icon_bar[1])
analysisBar$ci.max <- c(diff_geo_icon_bar[3], diff_geo_uni_bar[3], diff_uni_icon_bar[3])
analysisBar$ci.min <- c(diff_geo_icon_bar[2], diff_geo_uni_bar[2], diff_uni_icon_bar[2])
analysisBar$level  <- c(diff_geo_icon_bar[4], diff_geo_uni_bar[4], diff_uni_icon_bar[4])
analysisBar$ci_corr.max <- c(diff_geo_icon_bar[6], diff_geo_uni_bar[6], diff_uni_icon_bar[6])
analysisBar$ci_corr.min <- c(diff_geo_icon_bar[5], diff_geo_uni_bar[5], diff_uni_icon_bar[5])

analysisPie <- c()
analysisPie$name <- c("geo-icon", "geo-uni", "uni-icon")
analysisPie$pointEstimate <- c(diff_geo_icon_pie[1], diff_geo_uni_pie[1], diff_uni_icon_pie[1])
analysisPie$ci.max <- c(diff_geo_icon_pie[3], diff_geo_uni_pie[3], diff_uni_icon_pie[3])
analysisPie$ci.min <- c(diff_geo_icon_pie[2], diff_geo_uni_pie[2], diff_uni_icon_pie[2])
analysisPie$level  <- c(diff_geo_icon_pie[4], diff_geo_uni_pie[4], diff_uni_icon_pie[4])
analysisPie$ci_corr.max <- c(diff_geo_icon_pie[6], diff_geo_uni_pie[6], diff_uni_icon_pie[6])
analysisPie$ci_corr.min <- c(diff_geo_icon_pie[5], diff_geo_uni_pie[5], diff_uni_icon_pie[5])


###Plotting the differences

#Bar chart
datatoprintbar <- data.frame(factor(analysisBar$name), analysisBar$pointEstimate, analysisBar$ci.min, analysisBar$ci.max, analysisBar$level, analysisBar$ci_corr.min, analysisBar$ci_corr.max)
colnames(datatoprintbar) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintbar,analysisBar$name ,nbTechs = 3, ymin = -3, ymax = 3,  gray_line_interval = 1,"", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure9c-exp3_beauvis_diff_bar.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_beauvis_diff_bar.csv", collapse="_")
write.csv(datatoprintbar,file=tmp)

#Pie chart
datatoprintpie <- data.frame(factor(analysisPie$name), analysisPie$pointEstimate, analysisPie$ci.min, analysisPie$ci.max, analysisPie$level, analysisPie$ci_corr.min, analysisPie$ci_corr.max)
colnames(datatoprintpie) <- c("technique", "mean_time", "lowerBound_CI", "upperBound_CI", "corrected_CI", "lowerBound_CI_corr", "upperBound_CI_corr") #We use the name mean_time for the value of the mean even though it's not a time, it's just to parse the data for the plot
g <- barChart_corr(datatoprintpie,analysisPie$name ,nbTechs = 3, ymin = -3, ymax = 3,  gray_line_interval = 1, "", "","") #Avg. Thresholds. Error Bars, Bootstrap 95% CIs
print(g)

fname <- "results/Figure9d-exp3_beauvis_diff_pie.pdf"
ggsave(filename = fname, plot=g, width = 8, height= 1, device= pdf(), units = "in")
dev.off()

tmp <- paste(filename_analysis, "exp3_beauvis_diff_pie.csv", collapse="_")
write.csv(datatoprintpie,file=tmp)


```

